INSERT INTO WORD(ID, WORD_VALUE, PREMIUM) VALUES (-1, 'Community', 0);
INSERT INTO WORD(ID, WORD_VALUE, PREMIUM) VALUES (-2, 'Word', 0);
INSERT INTO WORD(ID, WORD_VALUE, PREMIUM) VALUES (-3, 'List', 0);
INSERT INTO WORD(ID, WORD_VALUE, PREMIUM) VALUES (-4, 'ßÜäÖфЫщЄїя-NonAscii', 0);
INSERT INTO WORD(ID, WORD_VALUE, PREMIUM) VALUES (-5, '@&?#ßÜäÖ-NonAlphabet', 0);
INSERT INTO WORD(ID, WORD_VALUE, PREMIUM) VALUES (-6, '6128349-Numeric', 0);
INSERT INTO WORD(ID, WORD_VALUE, PREMIUM) VALUES (-7, '', 0);
/*
INSERT INTO WORD(ID, WORD_VALUE, PREMIUM) VALUES (-8, 'Premium', 1);
INSERT INTO WORD(ID, WORD_VALUE, PREMIUM) VALUES (-9, 'Bonus', 1);
 */

INSERT INTO PREMIUM_WORD(ID, WORD_VALUE, SEQUENCE, LANGUAGE_CODE) VALUES (-1, 'this', 0, 'en');
INSERT INTO PREMIUM_WORD(ID, WORD_VALUE, SEQUENCE, LANGUAGE_CODE) VALUES (-2, 'is', 1, 'en');
INSERT INTO PREMIUM_WORD(ID, WORD_VALUE, SEQUENCE, LANGUAGE_CODE) VALUES (-3, 'premium', 2, 'en');

INSERT INTO PREMIUM_WORD(ID, WORD_VALUE, SEQUENCE, LANGUAGE_CODE) VALUES (-11, 'das', 0, 'de');
INSERT INTO PREMIUM_WORD(ID, WORD_VALUE, SEQUENCE, LANGUAGE_CODE) VALUES (-12, 'ist', 1, 'de');
INSERT INTO PREMIUM_WORD(ID, WORD_VALUE, SEQUENCE, LANGUAGE_CODE) VALUES (-13, 'Premium', 2, 'de');