# GLOBAL
quarkus.swagger-ui.path=/assignment-word-list/swagger-ui

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/word_list
quarkus.datasource.username=wordlist
quarkus.datasource.password=WordList_2024

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true

com.cgm.life.word.page.size.default=10
com.cgm.life.language.code.default=en

quarkus.package.uber-jar=true

quarkus.smallrye-openapi.info-title=Big Words API
quarkus.smallrye-openapi.info-version=1.0.1
quarkus.smallrye-openapi.info-description=Big Words simple service

# TEST
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:wordDB
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=


%test.quarkus.hibernate-orm.dialect=org.hibernate.dialect.H2Dialect
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.log.sql=false
%test.quarkus.hibernate-orm.sql-load-script=data-test.sql
%test.quarkus.http.port=9090

%test.quarkus.log.category."com.cgm.life".level=DEBUG