INSERT INTO WORD_USER(USERNAME, PASSWORD, ROLE) VALUES ('regular', '$2a$10$2GadPIs3jvRCcVgFly4NweGpSURdxKi2kTFf5RQZDjNnYdME7tcQe', 'endUser');
INSERT INTO WORD_USER(USERNAME, PASSWORD, ROLE) VALUES ('premium', '$2a$10$2GadPIs3jvRCcVgFly4NweGpSURdxKi2kTFf5RQZDjNnYdME7tcQe', 'bigWords');
INSERT INTO WORD_USER(USERNAME, PASSWORD, ROLE) VALUES ('admin', '$2a$10$2GadPIs3jvRCcVgFly4NweGpSURdxKi2kTFf5RQZDjNnYdME7tcQe', 'endUser, bigWords');
INSERT INTO WORD_USER(USERNAME, PASSWORD, ROLE) VALUES ('guest', '$2a$10$2GadPIs3jvRCcVgFly4NweGpSURdxKi2kTFf5RQZDjNnYdME7tcQe', '');