INSERT INTO PREMIUM_WORD(WORD_VALUE, SEQUENCE, LANGUAGE_CODE) VALUES ('this', 0, 'en');
INSERT INTO PREMIUM_WORD(WORD_VALUE, SEQUENCE, LANGUAGE_CODE) VALUES ('is', 1, 'en');
INSERT INTO PREMIUM_WORD(WORD_VALUE, SEQUENCE, LANGUAGE_CODE) VALUES ('premium', 2, 'en');

INSERT INTO PREMIUM_WORD(WORD_VALUE, SEQUENCE, LANGUAGE_CODE) VALUES ('das', 0, 'de');
INSERT INTO PREMIUM_WORD(WORD_VALUE, SEQUENCE, LANGUAGE_CODE) VALUES ('ist', 1, 'de');
INSERT INTO PREMIUM_WORD(WORD_VALUE, SEQUENCE, LANGUAGE_CODE) VALUES ('Premium', 2, 'de');
